### ISSUE TITLE
The default pose determination 

### ISSUE THREAD

**Issue by superkudo** [SeedV/SeedUnityVRKit#49]
When the screen can‘t track the arm or hand， we need the Avatar arm and hand stay in default pose， Looks normal.   when I put my arm down,  avator arm and hand is alse stay last position, don’t  looks normal

**Comment by henryouly** [comment]
This needs some more work. Essentially, you will need to:
1. Add a low-pass filter to determine if a `null` result is because of a temporary frame drop (e.g. when we add the null check in #46), or is because of the posture change. (A better fix is actually to analyze if the null result can be a result of sending too many frames to MP and reduce the frame pool size to avoid this false positive.)
2. If it's because the posture, Kalman filter should make the movement smooth and natural (moving the arm down).

**Comment by henryouly** [comment]
Because #54 fixes the `null` result, it might not be required (or at least make it less frequent)
